default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: my_post_dev

test:
  <<: *default
  database: my_post_test

production:
  <<: *default
  database: my_post_product
